language: go

sudo: false

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_success: never
    on_failure: always

go:
  - 1.5.4
  - 1.6.2

install:
  - go get github.com/Masterminds/glide
  - go get golang.org/x/tools/cmd/cover
  - make get

script :
  - make
  - make test
