language: go

sudo: false

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_success: never
    on_failure: always

go:
  - 1.6.2

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/stretchr/testify/assert
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
  - make get

script :
  - make
  - make test

after_success:
  - make coverage
