url: "http://10.0.161.177:7777/reputation/v1/malware"
interval: 0
snort_socket_timeout: 5
instances: [{
  min_score: 1,
  ip_blacklist: "iplists/black_1.list",
  ip_whitelist: "iplists/seen_1.list",
  hash_blacklist: "files/black_1.list",
  hash_whitelist: "files/seen_1.list",
  # snort_socket_path: "/etc/snort/0/cs/0"
  },{
  min_score: 5,
  ip_blacklist: "iplists/black_2.list",
  ip_whitelist: "iplists/seen_2.list",
  hash_blacklist: "files/black_2.list",
  hash_whitelist: "files/seen_2.list",
  # snort_socket_path: "/etc/snort/0/cs/1"
}]
