url: http://10.0.161.177:7777/reputation/v1/malware
min_score: 50
ip_blacklist: iplists/black.list
ip_whitelist: iplists/seen.list
hash_blacklist: files/black.list
hash_whitelist: files/seen.list
interval: 0
snort_socket_path: /etc/snort/0/cs
snort_socket_timeout: 5